/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desafio9;

import javax.swing.JOptionPane;

public class SelectordeLenguajes extends javax.swing.JFrame {

    /**
     * Creates new form SelectordeLenguajes
     */
    public SelectordeLenguajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaLenguajes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaLenguajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Java", "Python", "C++", "JavaScript", "C#" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaLenguajes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaLenguajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaLenguajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaLenguajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void listaLenguajesMouseClicked(java.awt.event.MouseEvent evt) {                                            
        if (evt.getClickCount() == 2) { // Detecta el doble clic
        // Obtener el lenguaje seleccionado
        String lenguaje = listaLenguajes.getSelectedValue();
        
        String info = "";
        
        switch (lenguaje) {
            case "Java":
                info = "Java: Lenguaje orientado a objetos, ideal para aplicaciones empresariales y Android.";
                break;
            case "Python":
                info = "Python: Popular por su sintaxis simple, usado en Data Science, IA y desarrollo web (Django/Flask).";
                break;
            case "JavaScript":
                info = "JavaScript: Esencial para el desarrollo web frontend y backend (Node.js).";
                break;
            default:
                info = "Lenguaje seleccionado: " + lenguaje + ". ¡Gran elección!";
        }
        
        // Mostrar la información
        JOptionPane.showMessageDialog(this, info, "Información de Lenguaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectordeLenguajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectordeLenguajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectordeLenguajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectordeLenguajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectordeLenguajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaLenguajes;
    // End of variables declaration                   
}
